### ISSUE TITLE
doorhanger behaviour on esc

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#104]
I was looking over the QA process and I think it is worth noting that when the doorhanger is opened - if the user clicks the `esc` key it logs the user's answer as "no(not broken)" 
The doorhanger will then not show again for that page.

I'm not sure if there is a way for use to customize the `esc` key behaviour or if it always triggers the secondary action.

@johannhof do you think this is acceptable behavior?

**Comment by johannhof** [comment]
Yeah :)

**Comment by johannhof** [comment]
To be more precise, I think if we let @godelstheory know of this behavior it's fine to leave it like that. I'll close this :)
