### ISSUE TITLE
The "Firefox Survey" pop-up is wrongly displayed more than 2 times for a specific domain and 3 times for a session

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#105]
**[Affected versions]:**
- Nightly 64.0a1

**[Affected Platforms]:**

- Windows 10x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to TP
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to ccn.com and refresh the page (max. 6 times) until the "Firefox Survey" doorhanger is displayed.
3. Navigate to another page of the same domain and refresh the page (max. 6 times) until the "Firefox Survey" doorhanger is displayed.
4. Navigate to another page of the same domain and refresh the page (max. 6 times).
5. Observe the behavior of the address bar.

**[Expected result]:**
- The "Firefox Survey" doorhanger is not displayed.

**[Actual result]:**
- The "Firefox Survey" doorhanger is displayed.

**[Notes]:**
- If you keep navigating and refreshing a page, the "Firefox Survey" doorhanger will wrongly be displayed more than 3 times per session. 
- Attached a screen recording of the issue: [Link ](https://drive.google.com/file/d/1lBv95TTry56ZmSwx1yOCOLgIi4XlTOY6/view)

**Comment by johannhof** [comment]
This works as expected, we only want to avoid showing the doorhanger if the user interacted with it.
