### ISSUE TITLE
Add list4 variation

### ISSUE THREAD

**Issue by fmarier** [mozilla/FastBlockShield#108]
This variant will only be tested with a timeout of 5 seconds. So there will only be:

* FB5L4
* ControlL4

(no *FB2L4*)

Here are the relevant prefs:
* `browser.safebrowsing.provider.mozilla.lists` = *(default value)*
* `urlclassifier.trackingAnnotationTable` = `test-track-simple,ads-track-digest256,social-track-digest256`
* `urlclassifier.trackingAnnotationWhitelistTable` = *(default value)*
* `urlclassifier.disallow_completions` = *(default value)*

**Comment by johannhof** [comment]
This was fixed by #115
