### ISSUE TITLE
Disable the default cookie restrictions explicitly in all variations

### ISSUE THREAD

**Issue by fmarier** [mozilla/FastBlockShield#110]
Just in case there is some screw-up in the way we run both Shield studies at once or that the prefs from Nightly accidentally make it to beta, maybe we should disable the default cookie restrictions explicitly in all branches.

@ehsan, what's the best way to do this? Set `network.cookie.cookieBehavior = 0`?

**Comment by ericawright** [comment]
I'm fairly certain shield will not enroll users in more than one study at a time, though it won't hurt to do this
