### ISSUE TITLE
Trackers are wrongly blocked on ControlL2 branch first time when navigating to https://www.huffingtonpost.co.uk/

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#112]
**[Affected versions]:**
- Beta 63.0b3

**[Affected Platforms]:**

- Windows 10 x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to ControlL2
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock add-on is installed.
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.huffingtonpost.co.uk/
3. Look for any blocked trackers in the console.

**[Expected result]:**
- No trackers displayed as blocked in the console while on "ControlL2" branch variation.

**[Actual result]:**
- Several trackers are wrongly blocked on the "ControlL2" branch variation. 

**[Notes]:**
- If I navigate again in another tab to the same website the trackers are not displayed as being blocked in the browser console. 
- Attached a screen recording of the issue: [Link](https://drive.google.com/file/d/1FNoOyv6od1EoJaERKgbOjSqgIEZ0HmS8/view) 
- Attached a copy of the browser console blocked trackers:
The resource at “https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10&appId=238320442863988” was blocked because content blocking is enabled.[Learn More] www.huffingtonpost.co.uk
Loading failed for the <script> with source “https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10&appId=238320442863988”. www.huffingtonpost.co.uk:1:1
The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled.[Learn More] www.huffingtonpost.co.uk
Loading failed for the <script> with source “https://platform.twitter.com/widgets.js”. www.huffingtonpost.co.uk:1:1
The resource at “https://cdn.taboola.com/libtrc/aol-huffingtonpost-uk/loader.js” was blocked because content blocking is enabled.[Learn More] www.huffingtonpost.co.uk
Loading failed for the <script> with source “https://cdn.taboola.com/libtrc/aol-huffingtonpost-uk/loader.js”. www.huffingtonpost.co.uk:1:1
The resource at “https://sb.scorecardresearch.com/beacon.js” was blocked because content blocking is enabled.[Learn More] www.huffingtonpost.co.uk
Loading failed for the <script> with source “https://sb.scorecardresearch.com/beacon.js”. www.huffingtonpost.co.uk:1:1
The resource at “https://connect.facebook.net/en_US/fbevents.js” was blocked because content blocking is enabled.[Learn More] www.huffingtonpost.co.uk
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”.

**Comment by Softvision-AndreeaCupsa** [comment]
I always make new profiles for each branch I test, just to make sure that no problems will occur.

**Comment by Softvision-AndreeaCupsa** [comment]
I didn't managed to reproduce this after I refreshed the page, or closed the tab, reopened another one and navigated again to the same website.

**Comment by johannhof** [comment]
So you're saying that the issue can't be reproduced at all?

**Comment by Softvision-AndreeaCupsa** [comment]
I managed to reproduce it on 2 profiles from 4, on the same branch, but I got different lists of trackers, small difference. I tried on other branches also, but I didn't managed to reproduce it there.

**Comment by Softvision-AndreeaCupsa** [comment]
I cannot reproduce this issue with the latest build from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1475424#c34) and also from the Github repository on Firefox Beta 63.0b6 on Windows 10 x64.
Considering this I will close this issue.
