### ISSUE TITLE
The "shield-study-addon" archived ping is not sent on  L1/L2/L3 branches

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#113]
**[Affected versions]:**
- Beta 63.0b3

**[Affected Platforms]:**

- Windows 10 x64
- Windows 7 x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to ControlL1
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock signed add-on is installed.
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate on a few websites that are known to have trackers and close the tab.
3. Open a new tab and navigate to "about:telemetry" page
4. Observe the archived pings section.

**[Expected result]:**
- "shield-study-addon" archived ping option should be displayed
 
**[Actual result]:**
- "shield-study-addon" archived ping option is not displayed

**[Notes]:**
- This issue is not reproducible with the L0 branch.
- Also "Loading failed for the <script> with source" error type are displayed in the browser console on the branches on which this issue is reproducible.
- Attached a screen recording of the issue: [Link ](https://drive.google.com/open?id=1kqkoYMLsKJzb-i2RinJ8jkybBSVeXV2D)

**Comment by johannhof** [comment]
This should have gotten fixed by #115
