### ISSUE TITLE
The "block tracker" shield icon is not displayed on L1,L2,L3 branches for possible blocked trackers

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#114]
**[Affected versions]:**
- Beta 63.0b3

**[Affected Platforms]:**

- Windows 10 x64
- Windows 7 x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to ControlL1
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock signed add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the DevTools, network section.
3. Navigate on a website that is known to have trackers.
4. Search for a shield icon near the domains in the Network section from Devtools.

**[Expected result]:**
- The shield icon is displayed near the tracking domains in the Network section from Devtools and when hovered "This URL matches a known tracker and it would be blocked with Content Blocking enabled" message appears.
 
**[Actual result]:**
- There is no shield icon displayed near the tracker domains in the Network section from Devtools.

**[Notes]:**
- This issue is only sometimes reproducible with the L0 branch.
- This might be cause by this issue: #113 
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1NUv1DgxdpuxQl64eHYaegMRZGhNWGjQg)

**Comment by johannhof** [comment]
This should have gotten fixed by #115
