### ISSUE TITLE
FastBlock experiment wrongly blocks trackers in Private Browsing Mode

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/FastBlockShield#116]
[Affected versions]:
- Firefox Beta, Version 63.0b4, Build ID 20180906162647

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "shieldStudy.logLevel" string pref is added with the "All" value.
- The "extensions.fastblock_shield_mozilla_org.test.variationName" string pref is added with the "FB2L0" value.
- FastBlock version 1.0.0 addon is installed from the GitHub repository.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open the Browser Console and open a new Private Window.
3. Navigate to a website (eg. cnn.com) and observe the Browser Console.

[Expected result]:
- No trackers are blocked in Private Browsing Mode.

[Actual result]:
- Trackers are blocked in Private Browsing Mode.

[Additional Notes]:
- The privacy.trackingprotection.pbmode.enabled pref is set to true.
- I have attached a screen recording of the issue:
![private mode trackers](https://user-images.githubusercontent.com/40393891/45285333-9e3e5700-b4eb-11e8-9b54-8f12eb7a936e.gif)

**Comment by johannhof** [comment]
Yeah, Tracking Protection is on in private windows, so this is expected.

**Comment by Softvision-PatriciuPop** [comment]
Yes, Tracking Protection is enabled, but navigating on the same page on a profile with FastBlock installed yelds an additional string in the console "and the rescource was classified as a slow tracking resource".
Without FastBlock:
![fb off](https://user-images.githubusercontent.com/40393891/45295919-f59ef000-b508-11e8-904a-ed0c2f642649.png)

With FastBlock:
![fb on](https://user-images.githubusercontent.com/40393891/45295921-f899e080-b508-11e8-84a1-0746d22e603a.png)

Since blocking Slow Loading Trackers is a feature of FastBlock are we absolutley sure the addon is not running in Private Browsing Mode ?

**Comment by Softvision-AndreeaCupsa** [comment]
Adding some additional information to this: 

On the FB branches, if you change the privacy.trackingprotection.pbmode.enabled pref value to false then trackers blocked by slow tracking will be displayed in the browser console while private browsing.

I am attaching 2 screenrecordings:
- [Link](https://drive.google.com/open?id=11S0WOfHg0p8HIR2wuG_z6fbXCxFPgUux)
- [Link ](https://drive.google.com/open?id=12a6-5-S5w_n_g5cORiR_T8VzG8jeGSfP)

Tested on Nightly 64.0a1 (2018-09-10) with the latest build from the Github Repository, on FB2L0 and FB5L4 branches.

**Comment by johannhof** [comment]
Yup, not an issue as long as we don't report it. Do you get any reports for private windows?

**Comment by Softvision-AndreeaCupsa** [comment]
No, no telemetry is sent in private mode.
