### ISSUE TITLE
Copy and design for notification bar

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#12]
- Change copy
- What type of user input should there be?
- what should it look like?

**Comment by ericawright** [comment]
<img width="420" alt="screen shot 2018-08-13 at 11 43 23 am" src="https://user-images.githubusercontent.com/10803178/44042386-1c37a418-9eee-11e8-8a5b-54fcbe8aa5c8.png">

**Comment by ericawright** [comment]
From @bryanbell:

It should have an icon, a title.
Remove the "x" in the top corner.
Make it look like it came from Firefox.
Add a "thank you" note after.
Don't hide on losing focus.

**Comment by bryanbell** [comment]
first pass 

https://mozilla.invisionapp.com/share/8RNJV40FTJA#/314691960_Artboard_1

**Comment by johannhof** [comment]
@bryanbell I think this a good direction, I like using the Firefox icon and the general tone. There's one issue in that it's not super straightforward for us as a Shield study to modify the layout of that dialog (this was a major pain for Monitor), so we can't do the radio group (and I'd also be worried that people wouldn't read it and just submit something).

Maybe something like this:

Did you reload the page in an attempt to clear up loading issues?

[ ] Don't ask me again on this site

[Yes] [No]

**Comment by johannhof** [comment]
And then maybe we just want both options in gray without a default choice in blue...
