### ISSUE TITLE
No telemetry is sent when the user reports a problem on a domain on which a previous interaction with content blocking was made

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FastBlockShield#125]
**[Affected versions]:
- Beta 63.0b5

**[Affected Platforms]:**
- Windows 10 x64

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to TP
	- Extensions.legacy.enabled;true
	- Xpinstall.signatures.required;false
- The Fastblock signed add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to cnn.com.
2. Refresh the page (max. 6 times) until the doorhanger is displayed and click the "No (works)(D)" button.
3. Open the "Content blocking" doorhanger from "Shield" icon and click on "Report a problem" button.
4. Enter some text or leave it empty and submit it.
5. Open the browser console (Ctrl+Shift+J) 
6. Look for the "user_reported_page_breakagage" ping in console and observe it's value.

**[Expected result]:**
- A ping with the "user_reported_page_breakagage" true value is sent

**[Actual results]:**
- No new ping is sent.

 **[Notes]:**
- This issue is also reproducible if the "Yes, (Broken)(F)" or "Disable Blocking For This Site" buttons were previously clicked.
- If you click "Disable Blocking For This Site" after the "No (works)(D)" or "Yes, (Broken)(F)"  buttons were clicked, another ping is sent with the corect value for "user_added_exception".
- This issue is not reproducible with the "Cookie Restriction" shield study, the build before the fix. The ping with the correct value for the "user_reported_page_breakagage" is sent after the tab is closed.
- Attached a screen recording of the issue:
https://drive.google.com/open?id=1nrN5cN-PNzo0TSPwvbLCPyRBnouoGAPu

**Comment by johannhof** [comment]
You need to do some navigation action to trigger the ping that contains `user_reported_page_breakagage`, I don't see you doing that in the recording. This is also why it's sent when you click "Disable Blocking For This Site".
