### ISSUE TITLE
Needed: Notification if trackers are on page.

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#15]
@johannhof
For #9 we need to be able to tell if any trackers were on the page, and NOT send telemetry if there are none.
Will this be a pref, or a notification of some sort?
How will I be able to get this info from TT and TB?

**Comment by johannhof** [comment]
Yeah, ugh, damn, so, there are two options for this, I think, depending on how you want to approach this:

- There's a [hasTrackingContentBlocked](https://searchfox.org/mozilla-central/rev/10e6320abc7fb0479032f0e95e9d61e4be194b9e/docshell/base/nsIDocShell.idl#605) attribute on the docShell of the content window. To access this you would have to inject a privileged frame script into the page from a WebExtension Experiment. That frame script could answer via message passing whether its document currently has blocked trackers based on the attribute. It seems like a bit of an effort but this may be the only way for us to access that information on demand. The downside is that resources could be blocked after we request the information.
- We could write a WEE that implements [nsIWebProgressListener](https://searchfox.org/mozilla-central/source/uriloader/base/nsIWebProgressListener.idl) to listen for the [onSecurityChange](https://searchfox.org/mozilla-central/rev/10e6320abc7fb0479032f0e95e9d61e4be194b9e/uriloader/base/nsIWebProgressListener.idl#447) function and trigger a callback in the WebExtension background script whenever we get passed a state that is blocking tracking content (see [browser-trackingprotection.js](https://searchfox.org/mozilla-central/rev/10e6320abc7fb0479032f0e95e9d61e4be194b9e/browser/base/content/browser-trackingprotection.js#199)). [This is the simplest example](https://searchfox.org/mozilla-central/rev/10e6320abc7fb0479032f0e95e9d61e4be194b9e/browser/components/extensions/parent/ext-tabs.js#1169) I could find on how to implement nsIWebProgressListener. I think I definitely prefer this approach.

In any case this sounds like it may warrant writing an own WebExtension Experiment just for this purpose. This should work for both FastBlock and TP but I have no idea whether we can (or want) to detect tailing.

@fmarier @ehsan is there anything I'm missing here?

Maybe there's a way to do this purely with WebExtension APIs, but I'm not aware of it. It would be cool if there was one.
