### ISSUE TITLE
Remove content script.

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#24]
Now that I'm using a framescript for access to nsIWebProgressListener, I can also use it to do everything the content script is doing.

note: `content` should be `window` in the FS

**Comment by johannhof** [comment]
I think we actually don't need the framescript, afaik `onSecurityChange` notifications will arrive in the parent as well. So unless you really need the framescript to resolve #22 I'd prefer to stick with a content script instead.

**Comment by ericawright** [comment]
I wasn't able to access the `docShell` to set up the listener from anywhere other than a FS, it could potentially be removed if you know of a better way to get to it? (and if I don't need it for #22 )

**Comment by johannhof** [comment]
The progress listener that updates most Firefox security UI in the chrome process listens on the tabbrowser (gBrowser on a chrome window), so that should work in our case as well https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/tabbrowser#m-addProgressListener

**Comment by johannhof** [comment]
...but looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1481252 we might actually end up still needing to query the docShell for the tracking attributes, so meh. :sweat_smile:

**Comment by ericawright** [comment]
won't be doing this
