### ISSUE TITLE
todo: private browsing

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#25]
ensure this does not show up in private browsing, nor safe mode

**Comment by ericawright** [comment]
Currently the popup does not show in private browsing (since we ignore private windows when sending the notifications) but we do send telemetry from private windows.

note: `"incognito": "not_allowed"` is not supported by firefox

**Comment by johannhof** [comment]
So why exactly do we want to not send the telemetry, considering that we're not sending identifying data about the website?

Like, I'm pretty sure that sending this in private mode is within policy for data review.

**Comment by ericawright** [comment]
My understanding is that the default settings for private browsing has tracker protection enabled, as well as the "do not track" message. I think we don't want to deal with whatever confusion this might cause in the data.

**Comment by johannhof** [comment]
Ah, of course. Can we filter for non-private windows in EveryWindow.jsm?

**Comment by ericawright** [comment]
Likely. I was thinking of filtering from the content script so we don't catch the load event. It would be nice if there was a filter that would broadly turn off everything though

**Comment by johannhof** [comment]
Don't think the content script can detect private windows, though.

**Comment by johannhof** [comment]
This will be fixed in #60

**Comment by johannhof** [comment]
Fixed in #60
