### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by groovecoder** [mozilla/FastBlockShield#28]
* [x] Document the repo set-up and run instructions - mostly uplifting bits and pieces from the study template content in `docs/`
* [x] Run thru [the PHD](https://docs.google.com/document/d/1LQdOFIZeoiD38NNMxvpm32bX6Urnv0KbEsGfgAuw5L8/edit?) again to make sure we're not missing something
* [x] Add some first simple user scenario testing instructions

**Comment by groovecoder** [comment]
See https://github.com/mozilla/FastBlockShield/pull/46 for user scenarios.

**Comment by ericawright** [comment]
This is essentially taken care of now, closing.
