### ISSUE TITLE
Create 4 control groups

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#32]
`studySetup.js`
- instead of weighting control as "4", create four separate control groups each weighted as "1"

`feature.js`
- add three more cases for "control" each with the same prefs set.

**Comment by johannhof** [comment]
I thought I understood this but I think I don't. @ericawright can you please explain the reasoning behind this change?

**Comment by ericawright** [comment]
This is to essentially give each control group a block list so that the data folks can compare directly what would have been blocked had TP or FB been enabled on that particular branch.

**Comment by johannhof** [comment]
Closed by #79 !
