### ISSUE TITLE
Consider reading variations from a JSON file

### ISSUE THREAD

**Issue by johannhof** [mozilla/FastBlockShield#34]
I've seen some studies do this, and I guess it tends to make it easier to parse for people coming into the project.

**Comment by ericawright** [comment]
I'm not sure what you mean by this - as in instead of the `weightedVariations` in `studySetup.js`?

**Comment by johannhof** [comment]
No, I meant the pref variations here: https://github.com/mozilla/FastBlockShield/blob/master/src/feature.js#L20
