### ISSUE TITLE
Block Lists

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#35]
confirm that this can be set with a pref
confirm the pref name
@johannhof

**Comment by ericawright** [comment]
the prefs are named:
1. urlclassifier.trackingAnnotationTable - string
2. urlclassifier.trackingAnnotationWhitelistTable - string

for 1: 
Set to "test-track-simple,fastblock1-track-digest256" for fastblock1, replace with "fastblock2" or "fastblock3" for the other variants.

for 2: 
Set to "test-trackwhite-simple,mozstd-trackwhite-digest256,fastblock1-trackwhite-digest256" for fastblock1, replace with fastblock2 for that second variant.
Note, this pref should be set to the default value for the fastblock3 variant.

**Comment by ericawright** [comment]
@fmarier What should I set this pref to when it is a tracking protection branch, not a fastblock branch?
We are testing 2 variations are fastblock, one at 3s and one at 5s, what versions do you consider those?

**Comment by fmarier** [comment]
> What should I set this pref to when it is a tracking protection branch, not a fastblock branch?

For tracking protection, you should have:

* `privacy.trackingprotection.enabled = true`
* `browser.fastblock.enabled = false`

There's no need to change any of the other prefs since they aren't used for tracking protection. Tracking protection relies on `urlclassifier.trackingTable` and `urlclassifier.trackingWhitelistTable` instead, and these two prefs should be set to their default values for the experiment.

> We are testing 2 variations are fastblock, one at 2s and one at 5s, what versions do you consider those?

Other than changing `browser.fastblock.timeout`, each variant (2000ms and 5000ms) will be subdivided into fastblock1, fastblock2, fastblock3 as above. Or did I misunderstand your question?

**Comment by ericawright** [comment]
@fmarier For this experiment we have 4 different block lists to be used with TP as well. Are the above prefs not for specifying which block list to use?

We will be setting `browser.fastblock.timeout`. These subdivisions 1, 2, 3 are not something I've heard about yet.

**Comment by fmarier** [comment]
> For this experiment we have 4 different block lists to be used with TP as well. Are the above prefs not for specifying which block list to use?

I thought we were only testing TP with the normal list (list 0). We've never talked about changing the list for TP in the product, so I'm not sure I understand why we'd test TP with a different list.

>  We will be setting browser.fastblock.timeout. These subdivisions 1, 2, 3 are not something I've heard about yet.

Sorry, by "fastblock1", "fastblock2", "fastblock3", I meant "list1", "list2", "list3".

So the fastblock branches would be:

- fastblock 2000ms list 0
- fastblock 2000ms list 1
- fastblock 2000ms list 2
- fastblock 2000ms list 3
- fastblock 5000ms list 0
- fastblock 5000ms list 1
- fastblock 5000ms list 2
- fastblock 5000ms list 3

**Comment by johannhof** [comment]
@fmarier @ericawright Ok, I made a comment in the PHD and let's try to find out!

https://docs.google.com/a/mozilla.com/document/d/1LQdOFIZeoiD38NNMxvpm32bX6Urnv0KbEsGfgAuw5L8/edit?disco=AAAACDQ4jGc

**Comment by johannhof** [comment]
I think #79 closed this.
