### ISSUE TITLE
Exlude profiles which already have ad-blockers/privacy add-ons and tracking protection.

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#5]
Client profiles are removed from the experimental sample which have ad-blockers or privacy add-ons installed. These include the following:
* uBlock Origin: uBlock0@raymondhill.net
* Adblock Plus: d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d                 
* Adblock: jid1-NIfFY2CA8fy1tg@jetpack
* NoScript: 73a6fe31-595d-460b-a920-fcc0f8843232
* Ghostery: firefox@ghostery.com         
* AdBlocker Ultimate: adblockultimate@adblockultimate.net
* Privacy Badger: jid1-MnnxcxisBPnSXQ@jetpack
* DuckDuckGo Privacy Essentials: 
* uMatrix: https://addons.mozilla.org/firefox/addon/umatrix/

**Comment by ericawright** [comment]
I am also expecting Normandy to filter out all non-default configurations of tracking protection prefs.

**Comment by mythmon** [comment]
That is possible. Please mention it in the PHD for this project, or relay it to someone on the S&I team. It needs to be part of the Normandy recipe's filter expression.

**Comment by ericawright** [comment]
Thanks for confirming! It's in the PHD already, but I could specifically list out the prefs we are concerned with.
