### ISSUE TITLE
Remove num_JS_exceptions

### ISSUE THREAD

**Issue by johannhof** [mozilla/FastBlockShield#52]
See #44, we need some kind of explanation on what this field in the example payload is supposed to mean.

**Comment by johannhof** [comment]
Question also asked here: https://docs.google.com/a/mozilla.com/document/d/1LQdOFIZeoiD38NNMxvpm32bX6Urnv0KbEsGfgAuw5L8/edit?disco=AAAACGCTgDw

**Comment by englehardt** [comment]
I suspect the "Javascript execution exceptions" listed in the doc was just left over from an earlier version that didn't list out all of the exceptions types. However, using it as "any other errors that aren't listed" seems safer to me.

**Comment by johannhof** [comment]
Alright, thanks!
