### ISSUE TITLE
How do we deal with Tracking Protection users in the FastBlock variations

### ISSUE THREAD

**Issue by johannhof** [mozilla/FastBlockShield#54]
Tanvi brought this up:

If we enable FastBlock for a user as part of their variation branch, but then (through the improved UI) that user discovers Tracking Protection and enables it, what do we do? Should we exclude the user from the experiment, or add a special flag that marks them?

cc @godelstheory

**Comment by saptarshiguha** [comment]
My suggestion is to add a special flag so it can be dealt with in the data munging/analysis stage.

**Comment by fmarier** [comment]
We'll want to exclude them (either during or after the study) because they will not experience FastBlock at all. Instead they will have the TP experience: faster page loads and more breakage.

**Comment by johannhof** [comment]
Another possibility would be hiding the Tracking Protection UI in the control center and about:preferences, making it virtually impossible for the user to enable it (unless they configure about:config, but then we've already kinda lost).

**Comment by johannhof** [comment]
We talked about this and think hiding the TP UI is the best option. Ehsan is adding a pref for this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1485199

Afterwards we can resolve this by flipping the pref in the FB variations.

**Comment by johannhof** [comment]
Bug 1485199 has landed.

**Comment by johannhof** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1486414 for adding prefs for about:preferences.
