### ISSUE TITLE
Error from sending telemetry on unload

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#63]
Sending telemetry on the "unload" event is causing an error.
<img width="580" alt="screen shot 2018-08-22 at 1 41 04 pm" src="https://user-images.githubusercontent.com/10803178/44480377-0d254000-a611-11e8-9fb2-043673ae385f.png">

**Comment by johannhof** [comment]
Yeah, I'm curious whether we can just ignore this error or not. My gut says the Promise resolving too late isn't an issue since the message still arrives, but for extra safety we might want to switch to the WebExtension event again...

**Comment by ericawright** [comment]
I worry since it used to always log when telemetry was sent, and we no longer get those logs. However, the tests say they are working...

**Comment by johannhof** [comment]
Resolved by #91
