### ISSUE TITLE
Cookies and site data

### ISSUE THREAD

**Issue by ericawright** [mozilla/FastBlockShield#75]
It has been suggested that toggling deny cookies and site data might remove `browser.storage.local`, test this.
or, filter users out who might have this pref set

**Comment by johannhof** [comment]
I don't think that's true, and if it was this would be a general issue for Shield studies, so I wouldn't worry about it too much.

**Comment by johannhof** [comment]
(We also don't rely a lot on `browser.storage.local`)

**Comment by ericawright** [comment]
Okay. I was thinking when we are marking "don't show again" on a site we'd be saving that in `browser.storage.local`.

**Comment by ericawright** [comment]
Figured I'd check this, and we are able to record in `browser.storage.local` that the popup has been interacted with with no problems.
