### ISSUE TITLE
Make sure we restore prefs to their previous state when the study ends

### ISSUE THREAD

**Issue by johannhof** [mozilla/FastBlockShield#77]
Currently I think we're just resetting the prefs, we should store them in browser storage and restore them.

**Comment by johannhof** [comment]
I think I'm actually wrong about this, I think we should just filter out any users that have already set any of the prefs we're trying to modify. @godelstheory, @fmarier, can you please confirm? I didn't find any specific mention of this in the PHD.

**Comment by fmarier** [comment]
Yes, I do think we should exclude anyone who has already customized any of the prefs we are setting.

That said, if you want to avoid having to reset prefs or keep a backup of the old ones, you can also change the default value of them (assuming WebExtensions expose that API too):

https://github.com/mozilla/sbv4-gradual-rollout/blob/master/bootstrap.js#L17
